spring.application.name=library

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_management
spring.datasource.username=postgres
spring.datasource.password=271297
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true